---
version: "3.8"

volumes:
  assets:
  pgdata:

networks:
  geoapi:
    driver: bridge

services:
  postgres_test:
    image: mdillon/postgis
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - geoapi
    stdin_open: true
    tty: true
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=test

  workers:
    image: taccaci/geoapi-workers:local
    volumes:
      - ..:/app
      - assets:/assets
    environment:
      - MAPILLARY_CLIENT_TOKEN=4866220476802272
      - FLASK_APP=/app/geoapi/app.py
      - APP_ENV=testing
      - ASSETS_BASE_DIR=/assets
      - TENANT
    stdin_open: true
    tty: true
    networks:
      - geoapi
    links:
      - "postgres_test:postgres_test"
    container_name: geoapiworkers
    hostname: geoapiworkers

  api:
    image: taccaci/geoapi-workers:local
    volumes:
      - ..:/app
      - assets:/assets
    ports:
      - 8000:8000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - FLASK_APP=/app/geoapi/app.py
      - APP_ENV=testing
      - ASSETS_BASE_DIR=/assets
      - TENANT
    stdin_open: true
    tty: true
    networks:
      - geoapi
    links:
      - "postgres_test:postgres_test"
    container_name: geoapi
    hostname: geoapi
    depends_on:
      - postgres_test
