services:
  postgres:
    image: postgis/postgis:18-3.6-alpine
    env_file: ../../../secret.env # username/password
    volumes:
      - /database:/var/lib/postgresql/
      - ./postgresql.conf:/var/lib/postgresql/18/docker/postgresql.conf:ro  # Comment out on initial db setup run!
    ports:
      - "5432:5432"
    stdin_open: true
    tty: true
    restart: always
    container_name: geoapi_postgres
