sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - docker build --cache-from taccaci/geoapi -t taccaci/geoapi:latest .

before_script:
  # Disable services enabled by default
  - sudo service mysql stop
  - sudo service postgresql stop

script:
  - docker network create -d bridge test
  - docker run -d --net=test -p 5432:5432 -e POSTGRES_DB=test -e POSTGRES_USER=dev -e POSTGRES_PASSWORD=dev --hostname=postgres --name=postgres mdillon/postgis
  - docker run --net=test -e APP_ENV=testing taccaci/geoapi pytest
