sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - docker build --cache-from taccaci/geoapi -t taccaci/geoapi:latest .

script:
  - docker network create -d bridge test
  - docker run -d -p 5432:5432 --network=test -e POSTGRES_DB=test -e POSTGRES_USER=dev -e POSTGRES_PASSWORD=dev --hostname=postgres --name=postgres mdillon/postgis
  - docker run --network=test -e APP_ENV=testing taccaci/geoapi pytest
