language: generic
sudo: required
env:
  - GIT_HASH=$(git log --format=%h -1)
services:
  - docker

jobs:
  include:
    - name: "geoapi: unit tests / container"
      before_script:
      - docker pull taccaci/geoapi:latest
      - docker build --cache-from taccaci/geoapi:latest -t taccaci/geoapi:latest .
      - sudo mkdir /assets
      - sudo service mysql stop
      - sudo service postgresql stop
      - docker network create -d bridge test
      - docker run -d --net=test -p 5432:5432 -e POSTGRES_DB=test -e POSTGRES_USER=dev -e POSTGRES_PASSWORD=dev --hostname=postgres --name=postgres mdillon/postgis
      - sleep 5
      script:
      - docker run --net=test -e APP_ENV=testing taccaci/geoapi:latest pytest --cov=geoapi -m "not worker"
      before_deploy:
         - docker tag taccaci/geoapi:latest taccaci/geoapi:$(GIT_HASH)
         - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      deploy:
        provider: script
        script:
          - docker push taccaci/geoapi:latest
          - docker push taccaci/geoapi:$GIT_HASH)
        on:
          branch: master
    - name: "geoapi-workers: unit tests / container"
      before_script:
      - docker pull taccaci/geoapi-workers:latest
      - docker build --cache-from taccaci/geoapi-workers:latest -t taccaci/geoapi-workers:latest -f Dockerfile.potree .
      - sudo mkdir /assets
      - sudo service mysql stop
      - sudo service postgresql stop
      - docker network create -d bridge test
      - docker run -d --net=test -p 5432:5432 -e POSTGRES_DB=test -e POSTGRES_USER=dev -e POSTGRES_PASSWORD=dev --hostname=postgres --name=postgres mdillon/postgis
      - sleep 5
      script:
      - docker run --net=test -e APP_ENV=testing taccaci/geoapi-workers:latest pytest --cov=geoapi -m "worker"
      before_deploy:
         - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
         - docker tag taccaci/geoapi-workers:latest taccaci/geoapi-workers:$(GIT_HASH)
      deploy:
        provider: script
        script:
          - docker push taccaci/geoapi-workers:latest
          - docker push taccaci/geoapi-workers:$(GIT_HASH)
        on:
          branch: master
