pipelines:
  default:
    - parallel:
      - step:
          caches:
            - docker
          services:
            - postgres
            - docker
          script:
            - docker build -t geoapi_api:latest .
            - docker run --rm --add-host="host.docker.internal:$BITBUCKET_DOCKER_HOST_INTERNAL" -e APP_ENV=testing -e DB_HOST=localhost -v $(pwd):/test_dir -w /test_dir geoapi_api:latest pytest geoapi
definitions:
  services:
    postgres:
      image: mdillon/postgis
      environment:
        POSTGRES_DB: test
        POSTGRES_USER: dev
        POSTGRES_PASSWORD: dev