pipelines:
  default:
    - parallel:
      - step:
          caches:
            - docker
          services:
            - postgres
            - docker
          script:
            - docker build -t geoapi_api:latest .
            - docker run --rm -p 5432:5432 -e APP_ENV=testing -v $(pwd):/test_dir -w /test_dir geoapi_api:latest pytest geoapi
definitions:
  services:
    postgres:
      image: mdillon/postgis
      environment:
        POSTGRES_DB: test
        POSTGRES_USER: dev
        POSTGRES_PASSWORD: dev