pipelines:
  default:
    - parallel:
      - step:
          image: python:3.7
          caches:
            - pip
          services:
            - postgres
          script:
            - pip install -r requirements.txt
            - APP_ENV=testing pytest
definitions:
  services:
    postgres:
      image: mdillon/postgis
      environment:
        POSTGRES_DB: test
        POSTGRES_USER: dev
        POSTGRES_PASSWORD: dev