pipelines:
  default:
    - parallel:
      - step:
          image: python:3.7
          caches:
            - docker
          services:
            - postgres
            - docker
          script:
            - docker-compose build api
            - docker run --rm -e APP_ENV=testing -v $(pwd):/test_dir -w /test_dir geoapi_api:latest pytest geoapi
definitions:
  services:
    postgres:
      image: mdillon/postgis
      environment:
        POSTGRES_DB: test
        POSTGRES_USER: dev
        POSTGRES_PASSWORD: dev