---
version: "3"

volumes:
  assets:
  pgdata:

networks:
  geoapi:

services:

  rabbitmq:
    image: rabbitmq
    networks:
      - geoapi
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev
      - RABBITMQ_DEFAULT_VHOST=dev

  postgres:
    image: mdillon/postgis
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - geoapi
    container_name: geoapi_postgres
    hostname: geoapi_postgres
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=dev

  nginx:
    image: nginx
    ports:
      - 8888:80
    volumes:
      - assets:/assets
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - geoapi


  workers:
    build:
      context: .
      dockerfile: ./Dockerfile.potree
    networks:
      - geoapi
    volumes:
      - .:/app
      - assets:/assets
    environment:
      - FLASK_APP=/app/geoapi/app.py
      - APP_ENV=development
      - ASSETS_BASE_DIR=/assets
    stdin_open: true
    tty: true
    container_name: geoapiworkers
    hostname: geoapiworkers
    command: "celery -A celery_app worker -l info"

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - geoapi
    volumes:
      - .:/app
      - assets:/assets
    ports:
      - 8000:8000
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - FLASK_APP=/app/geoapi/app.py
      - APP_ENV=development
      - ASSETS_BASE_DIR=/assets
    stdin_open: true
    tty: true
    container_name: geoapi
    hostname: geoapi
    command: "gunicorn -w 4 -b 0.0.0.0:8000 geoapi.app:app --reload"