[pytest]
markers =
    worker: tests that require geoapi worker
# defaults options sets to be not worker
addopts = -m "not worker"

# Remove after https://tacc-main.atlassian.net/browse/WG-694
filterwarnings =
    ignore::litestar.utils.deprecation.LitestarDeprecationWarning
