apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata3
  namespace: geoapi-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 750Gi
  storageClassName: rbd-new
