"""empty message

Revision ID: 03c3d62d3b11
Revises: 77346f8d9025
Create Date: 2022-03-11 04:14:03.819119

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03c3d62d3b11"
down_revision = "77346f8d9025"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "imported_file", sa.Column("successful_import", sa.Boolean(), nullable=True)
    )

    # Any existing rows correspond to successfully imported files
    op.execute("UPDATE imported_file SET successful_import = true")

    op.alter_column("imported_file", "successful_import", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("imported_file", "successful_import")
    # ### end Alembic commands ###
