"""empty message

Revision ID: 0a10e4e1ea0c
Revises: 8bb0c45d987d
Create Date: 2022-04-18 20:52:25.172291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a10e4e1ea0c'
down_revision = '8bb0c45d987d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streetview_sequence', sa.Column('organization_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_streetview_sequence_organization_id'), 'streetview_sequence', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streetview_sequence_organization_id'), table_name='streetview_sequence')
    op.drop_column('streetview_sequence', 'organization_id')
    # ### end Alembic commands ###
