"""empty message

Revision ID: 0f734dd05e3f
Revises: 15e9e94d699f
Create Date: 2020-01-21 21:19:34.481472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f734dd05e3f'
down_revision = '15e9e94d699f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_clouds', sa.Column('files_info', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point_clouds', 'files_info')
    )
    # ### end Alembic commands ###
