"""empty message

Revision ID: 15e9e94d699f
Revises: 759f0cedcc98
Create Date: 2020-01-21 01:21:17.903268

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "15e9e94d699f"
down_revision = "759f0cedcc98"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feature_assets", sa.Column("original_path", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_feature_assets_original_path"),
        "feature_assets",
        ["original_path"],
        unique=False,
    )
    op.drop_index("ix_feature_assets_display_path", table_name="feature_assets")
    op.drop_index("idx_features_the_geom", table_name="features")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_feature_assets_display_path",
        "feature_assets",
        ["display_path"],
        unique=False,
    )
    op.drop_index(op.f("ix_feature_assets_original_path"), table_name="feature_assets")
    op.drop_column("feature_assets", "original_path")
    # ### end Alembic commands ###
