"""Add migration of spatial index

Revision ID: f2d7f797c82a
Revises: 968f358e102a
Create Date: 2024-12-11 03:51:58.509951

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "f2d7f797c82a"
down_revision = "968f358e102a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_features_the_geom",
        "features",
        ["the_geom"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_features_the_geom", table_name="features", postgresql_using="gist"
    )
    # ### end Alembic commands ###
