"""remove_ObservableDataProject

Revision ID: 1040b620b32f
Revises: f2d7f797c82a
Create Date: 2024-12-11 17:53:36.850536

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1040b620b32f"
down_revision = "f2d7f797c82a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_observable_data_projects_project_id", table_name="observable_data_projects"
    )
    op.drop_table("observable_data_projects")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "observable_data_projects",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_date",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("system_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("path", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("watch_content", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name="observable_data_projects_project_id_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="observable_data_projects_pkey"),
        sa.UniqueConstraint(
            "system_id", "path", name="observable_data_projects_system_id_path_key"
        ),
    )
    op.create_index(
        "ix_observable_data_projects_project_id",
        "observable_data_projects",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###
