"""add_designsafe_project_id_column

Revision ID: 9ff599c0a0b4
Revises: 898a088d94d3
Create Date: 2025-11-19 15:34:51.471586

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ff599c0a0b4"
down_revision = "898a088d94d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feature_assets",
        sa.Column(
            "designsafe_project_id",
            sa.String(),
            nullable=True,
            comment="DesignSafe project ID, e.g. 'PRJ-1234', associated with current_system/original_system",
        ),
    )
    op.create_index(
        op.f("ix_feature_assets_designsafe_project_id"),
        "feature_assets",
        ["designsafe_project_id"],
        unique=False,
    )
    op.add_column(
        "projects", sa.Column("designsafe_project_id", sa.String(), nullable=True)
    )
    op.add_column(
        "tile_servers",
        sa.Column(
            "designsafe_project_id",
            sa.String(),
            nullable=True,
            comment="DesignSafe project ID, e.g. 'PRJ-1234', associated with current_system/original_system",
        ),
    )
    op.create_index(
        op.f("ix_tile_servers_designsafe_project_id"),
        "tile_servers",
        ["designsafe_project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tile_servers_designsafe_project_id"), table_name="tile_servers"
    )
    op.drop_column("tile_servers", "designsafe_project_id")
    op.drop_column("projects", "designsafe_project_id")
    op.drop_index(
        op.f("ix_feature_assets_designsafe_project_id"), table_name="feature_assets"
    )
    op.drop_column("feature_assets", "designsafe_project_id")
    # ### end Alembic commands ###
