"""add_original_system_to_feature_asset

Revision ID: f5f3cfac6089
Revises: ba8b92fc7ead
Create Date: 2025-10-30 22:12:13.034836

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5f3cfac6089"
down_revision = "ba8b92fc7ead"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feature_assets", sa.Column("original_system", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_feature_assets_original_system"),
        "feature_assets",
        ["original_system"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_feature_assets_original_system"), table_name="feature_assets"
    )
    op.drop_column("feature_assets", "original_system")
    # ### end Alembic commands ###
