"""add_tracking_info_to_tile_layer

Revision ID: 898a088d94d3
Revises: 3eba8dc7e4a9
Create Date: 2025-11-10 03:31:14.410321

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "898a088d94d3"
down_revision = "3eba8dc7e4a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "feature_assets",
        "original_system",
        existing_type=sa.VARCHAR(),
        comment="Tapis system where the original file was sourced from",
        existing_nullable=True,
    )
    op.alter_column(
        "feature_assets",
        "original_path",
        existing_type=sa.VARCHAR(),
        comment="Original file path on the source system",
        existing_nullable=True,
    )
    op.alter_column(
        "feature_assets",
        "current_path",
        existing_type=sa.VARCHAR(),
        comment="Current file path (updated if file is published or moved)",
        existing_nullable=True,
    )
    op.alter_column(
        "feature_assets",
        "current_system",
        existing_type=sa.VARCHAR(),
        comment="Current Tapis system (updated if file is published or moved)",
        existing_nullable=True,
    )
    op.alter_column(
        "feature_assets",
        "is_on_public_system",
        existing_type=sa.BOOLEAN(),
        comment="Whether the current_system is publicly accessible",
        existing_nullable=True,
    )
    op.alter_column(
        "feature_assets",
        "last_public_system_check",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp of last public accessibility check",
        existing_nullable=True,
    )
    op.add_column(
        "tile_servers",
        sa.Column(
            "current_path",
            sa.String(),
            nullable=True,
            comment="Current file path (updated if file is published or moved)",
        ),
    )
    op.add_column(
        "tile_servers",
        sa.Column(
            "current_system",
            sa.String(),
            nullable=True,
            comment="Current Tapis system (updated if file is published or moved)",
        ),
    )
    op.add_column(
        "tile_servers",
        sa.Column(
            "is_on_public_system",
            sa.Boolean(),
            nullable=True,
            comment="Whether the current_system is publicly accessible",
        ),
    )
    op.add_column(
        "tile_servers",
        sa.Column(
            "last_public_system_check",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of last public accessibility check",
        ),
    )
    op.alter_column(
        "tile_servers",
        "original_system",
        existing_type=sa.VARCHAR(),
        comment="Tapis system where the original file was sourced from",
        existing_comment="Tapis system where the original file was sourced from (if applicable)",
        existing_nullable=True,
    )
    op.alter_column(
        "tile_servers",
        "original_path",
        existing_type=sa.VARCHAR(),
        comment="Original file path on the source system",
        existing_comment="Original file path on the source system (if applicable)",
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_tile_servers_current_path"),
        "tile_servers",
        ["current_path"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tile_servers_current_system"),
        "tile_servers",
        ["current_system"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tile_servers_original_path"),
        "tile_servers",
        ["original_path"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tile_servers_original_path"), table_name="tile_servers")
    op.drop_index(op.f("ix_tile_servers_current_system"), table_name="tile_servers")
    op.drop_index(op.f("ix_tile_servers_current_path"), table_name="tile_servers")
    op.alter_column(
        "tile_servers",
        "original_path",
        existing_type=sa.VARCHAR(),
        comment="Original file path on the source system (if applicable)",
        existing_comment="Original file path on the source system",
        existing_nullable=True,
    )
    op.alter_column(
        "tile_servers",
        "original_system",
        existing_type=sa.VARCHAR(),
        comment="Tapis system where the original file was sourced from (if applicable)",
        existing_comment="Tapis system where the original file was sourced from",
        existing_nullable=True,
    )
    op.drop_column("tile_servers", "last_public_system_check")
    op.drop_column("tile_servers", "is_on_public_system")
    op.drop_column("tile_servers", "current_system")
    op.drop_column("tile_servers", "current_path")
    op.alter_column(
        "feature_assets",
        "last_public_system_check",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp of last public accessibility check",
        existing_nullable=True,
    )
    op.alter_column(
        "feature_assets",
        "is_on_public_system",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Whether the current_system is publicly accessible",
        existing_nullable=True,
    )
    op.alter_column(
        "feature_assets",
        "current_system",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Current Tapis system (updated if file is published or moved)",
        existing_nullable=True,
    )
    op.alter_column(
        "feature_assets",
        "current_path",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Current file path (updated if file is published or moved)",
        existing_nullable=True,
    )
    op.alter_column(
        "feature_assets",
        "original_path",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Original file path on the source system",
        existing_nullable=True,
    )
    op.alter_column(
        "feature_assets",
        "original_system",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Tapis system where the original file was sourced from",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
