"""add_system_path_to_tile_server

Revision ID: ba8b92fc7ead
Revises: 9f3dc3155741
Create Date: 2025-10-06 22:05:37.954793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8b92fc7ead'
down_revision = '9f3dc3155741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tile_servers', sa.Column('original_system', sa.String(), nullable=True, comment='Tapis system where the original file was sourced from (if applicable)'))
    op.add_column('tile_servers', sa.Column('original_path', sa.String(), nullable=True, comment='Original file path on the source system (if applicable)'))
    op.create_index(op.f('ix_tile_servers_original_system'), 'tile_servers', ['original_system'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tile_servers_original_system'), table_name='tile_servers')
    op.drop_column('tile_servers', 'original_path')
    op.drop_column('tile_servers', 'original_system')
    # ### end Alembic commands ###
