"""add_FileLocationCheck

Revision ID: 3eba8dc7e4a9
Revises: f5f3cfac6089
Create Date: 2025-11-06 14:43:16.639237

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3eba8dc7e4a9"
down_revision = "f5f3cfac6089"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "public_system_access_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_files", sa.Integer(), nullable=True),
        sa.Column("files_checked", sa.Integer(), nullable=True),
        sa.Column("files_failed", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_public_system_access_checks_project_id_projects"),
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_public_system_access_checks_task_id_tasks"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_public_system_access_checks")),
    )
    op.create_index(
        op.f("ix_public_system_access_checks_project_id"),
        "public_system_access_checks",
        ["project_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_public_system_access_checks_task_id"),
        "public_system_access_checks",
        ["task_id"],
        unique=False,
    )
    op.add_column(
        "feature_assets", sa.Column("current_path", sa.String(), nullable=True)
    )
    op.add_column(
        "feature_assets", sa.Column("current_system", sa.String(), nullable=True)
    )
    op.add_column(
        "feature_assets", sa.Column("is_on_public_system", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "feature_assets",
        sa.Column(
            "last_public_system_check", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_feature_assets_current_path"),
        "feature_assets",
        ["current_path"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feature_assets_current_system"),
        "feature_assets",
        ["current_system"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feature_assets_current_system"), table_name="feature_assets")
    op.drop_index(op.f("ix_feature_assets_current_path"), table_name="feature_assets")
    op.drop_column("feature_assets", "last_public_system_check")
    op.drop_column("feature_assets", "is_on_public_system")
    op.drop_column("feature_assets", "current_system")
    op.drop_column("feature_assets", "current_path")
    op.drop_index(
        op.f("ix_public_system_access_checks_task_id"),
        table_name="public_system_access_checks",
    )
    op.drop_index(
        op.f("ix_public_system_access_checks_project_id"),
        table_name="public_system_access_checks",
    )
    op.drop_table("public_system_access_checks")
    # ### end Alembic commands ###
