"""add_token_expires_at_to_streetview

Revision ID: 9ca03b666aee
Revises: 1040b620b32f
Create Date: 2025-03-18 20:13:21.188366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca03b666aee'
down_revision = '1040b620b32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streetview', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streetview', 'token_expires_at')
    # ### end Alembic commands ###
