"""add_project_id_and_last_message_to_task

Revision ID: 9f3dc3155741
Revises: 60f005164287
Create Date: 2025-10-06 21:48:00.414391

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9f3dc3155741"
down_revision = "60f005164287"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("project_id", sa.Integer(), nullable=True))
    op.add_column("tasks", sa.Column("latest_message", sa.String(), nullable=True))
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_tasks_project_id_projects"),
        "tasks",
        "projects",
        ["project_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "tile_servers",
        "url",
        existing_type=sa.VARCHAR(),
        comment="For internal=true: file path to asset (e.g., /assets/3/uuid.cog.tif).For internal=false: full tile URL template with {z}/{x}/{y} placeholders.",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tile_servers",
        "url",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="For internal=true: file path to asset (e.g., /assets/3/uuid.cog.tif).For internal=false: full tile URL template with {z}/{x}/{y} placeholders.",
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("fk_tasks_project_id_projects"), "tasks", type_="foreignkey"
    )
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_column("tasks", "latest_message")
    op.drop_column("tasks", "project_id")
    # ### end Alembic commands ###
