"""empty message

Revision ID: 203e14cdb88b
Revises: 63500bc39b63
Create Date: 2020-12-02 21:14:05.383400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203e14cdb88b'
down_revision = '63500bc39b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tile_servers', sa.Column('zIndex', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tile_servers', 'zIndex')
    # ### end Alembic commands ###
