"""empty message

Revision ID: 27c3fcfc55fe
Revises: 
Create Date: 2019-09-27 15:13:07.267482

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27c3fcfc55fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('jwt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('the_geom', geoalchemy2.types.Geometry(srid=4326), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('styles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_project_id'), 'features', ['project_id'], unique=False)
    op.create_index('ix_features_properties', 'features', ['properties'], unique=False, postgresql_using='gin')
    op.create_table('observable_data_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('system_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_id', 'path')
    )
    op.create_index(op.f('ix_observable_data_projects_project_id'), 'observable_data_projects', ['project_id'], unique=False)
    op.create_table('overlays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('minLat', sa.Numeric(), nullable=False),
    sa.Column('minLon', sa.Numeric(), nullable=False),
    sa.Column('maxLat', sa.Numeric(), nullable=False),
    sa.Column('maxLon', sa.Numeric(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overlays_project_id'), 'overlays', ['project_id'], unique=False)
    op.create_table('projects_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_table('feature_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('original_path', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_assets_feature_id'), 'feature_assets', ['feature_id'], unique=False)
    op.create_index(op.f('ix_feature_assets_original_path'), 'feature_assets', ['original_path'], unique=False)
    op.create_table('point_clouds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('conversion_parameters', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_clouds_feature_id'), 'point_clouds', ['feature_id'], unique=False)
    op.create_index(op.f('ix_point_clouds_project_id'), 'point_clouds', ['project_id'], unique=False)
    op.create_index(op.f('ix_point_clouds_task_id'), 'point_clouds', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():

    op.drop_index(op.f('ix_point_clouds_task_id'), table_name='point_clouds')
    op.drop_index(op.f('ix_point_clouds_project_id'), table_name='point_clouds')
    op.drop_index(op.f('ix_point_clouds_feature_id'), table_name='point_clouds')
    op.drop_table('point_clouds')
    op.drop_index(op.f('ix_feature_assets_original_path'), table_name='feature_assets')
    op.drop_index(op.f('ix_feature_assets_feature_id'), table_name='feature_assets')
    op.drop_table('feature_assets')
    op.drop_table('projects_users')
    op.drop_index(op.f('ix_overlays_project_id'), table_name='overlays')
    op.drop_table('overlays')
    op.drop_index(op.f('ix_observable_data_projects_project_id'), table_name='observable_data_projects')
    op.drop_table('observable_data_projects')
    op.drop_index('ix_features_properties', table_name='features')
    op.drop_index(op.f('ix_features_project_id'), table_name='features')
    op.drop_table('features')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('projects')
    # ### end Alembic commands ###
