"""empty message

Revision ID: 3aaf2104296f
Revises: 63e1135553fe
Create Date: 2022-04-01 16:26:38.923325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aaf2104296f'
down_revision = '63e1135553fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects_streetview_instances',
    sa.Column('streetview_instance_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['streetview_instance_id'], ['streetview_instance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('streetview_instance_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects_streetview_instances')
    # ### end Alembic commands ###
