"""empty message

Revision ID: 3f9a78c126da
Revises: 969eaf2b8f5e
Create Date: 2020-04-01 23:09:42.102427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9a78c126da'
down_revision = '969eaf2b8f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imported_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imported_file_path'), 'imported_file', ['path'], unique=False)
    op.create_index(op.f('ix_imported_file_project_id'), 'imported_file', ['project_id'], unique=False)
    op.create_index(op.f('ix_imported_file_system_id'), 'imported_file', ['system_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imported_file_system_id'), table_name='imported_file')
    op.drop_index(op.f('ix_imported_file_project_id'), table_name='imported_file')
    op.drop_index(op.f('ix_imported_file_path'), table_name='imported_file')
    op.drop_table('imported_file')
    # ### end Alembic commands ###
