"""empty message

Revision ID: 63500bc39b63
Revises: 8181e4dea4ad
Create Date: 2020-12-01 17:18:27.820413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63500bc39b63'
down_revision = '8181e4dea4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.drop_index('idx_features_the_geom', table_name='features')
    op.add_column('tile_servers', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tile_servers_project_id'), 'tile_servers', ['project_id'], unique=False)
    op.create_foreign_key(None, 'tile_servers', 'projects', ['project_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tile_servers', type_='foreignkey')
    op.drop_index(op.f('ix_tile_servers_project_id'), table_name='tile_servers')
    op.drop_column('tile_servers', 'project_id')
    # op.create_index('idx_features_the_geom', 'features', ['the_geom'], unique=False)
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
