"""empty message

Revision ID: 759f0cedcc98
Revises: 27c3fcfc55fe
Create Date: 2020-01-20 22:30:23.184464

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "759f0cedcc98"
down_revision = "27c3fcfc55fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feature_assets") as bop:
        bop.alter_column("original_path", new_column_name="display_path")
    op.create_index(
        op.f("ix_feature_assets_display_path"),
        "feature_assets",
        ["display_path"],
        unique=False,
    )
    op.drop_index("ix_feature_assets_original_path", table_name="feature_assets")
    op.drop_constraint(
        "point_clouds_feature_id_fkey", "point_clouds", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "point_clouds",
        "features",
        ["feature_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "point_clouds", type_="foreignkey")
    op.create_foreign_key(
        "point_clouds_feature_id_fkey",
        "point_clouds",
        "features",
        ["feature_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_index(
        "ix_feature_assets_original_path",
        "feature_assets",
        ["original_path"],
        unique=False,
    )
    op.drop_index(op.f("ix_feature_assets_display_path"), table_name="feature_assets")
    # ### end Alembic commands ###
