"""empty message

Revision ID: 77346f8d9025
Revises: a1f677535e21
Create Date: 2021-06-21 17:39:50.547358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77346f8d9025'
down_revision = 'a1f677535e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observable_data_projects', sa.Column('watch_content', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observable_data_projects', 'watch_content')
    # ### end Alembic commands ###
