"""empty message

Revision ID: 8bb0c45d987d
Revises: b014b0e37b0b
Create Date: 2022-04-13 21:31:26.876517

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8bb0c45d987d"
down_revision = "b014b0e37b0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "streetview_sequence", sa.Column("feature_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "streetview_sequence", sa.Column("task_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_streetview_sequence_feature_id"),
        "streetview_sequence",
        ["feature_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_streetview_sequence_task_id"),
        "streetview_sequence",
        ["task_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "streetview_sequence",
        "features",
        ["feature_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.create_foreign_key(None, "streetview_sequence", "tasks", ["task_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "streetview_sequence", type_="foreignkey")
    op.drop_constraint(None, "streetview_sequence", type_="foreignkey")
    op.drop_index(
        op.f("ix_streetview_sequence_task_id"), table_name="streetview_sequence"
    )
    op.drop_index(
        op.f("ix_streetview_sequence_feature_id"), table_name="streetview_sequence"
    )
    op.drop_column("streetview_sequence", "task_id")
    op.drop_column("streetview_sequence", "feature_id")
    # ### end Alembic commands ###
