"""empty message

Revision ID: 969eaf2b8f5e
Revises: 0f734dd05e3f
Create Date: 2020-03-26 17:34:35.110269

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "969eaf2b8f5e"
down_revision = "0f734dd05e3f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("status", sa.String(length=256), nullable=True),
        sa.Column("message", sa.String(length=512), nullable=True),
        sa.Column("viewed", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_username"), "notifications", ["username"], unique=False
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notifications_username"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
