"""empty message

Revision ID: 9d043dc43f64
Revises: 3f9a78c126da
Create Date: 2020-12-16 21:04:16.261270

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9d043dc43f64"
down_revision = "3f9a78c126da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tile_servers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("attribution", sa.String(), nullable=False),
        sa.Column(
            "tileOptions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("uiOptions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tile_servers_project_id"), "tile_servers", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tile_servers_project_id"), table_name="tile_servers")
    op.drop_table("tile_servers")
    # ### end Alembic commands ###
