"""empty message

Revision ID: dc0c2f6ba473
Revises: 0a10e4e1ea0c
Create Date: 2022-08-02 02:54:09.836110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0c2f6ba473'
down_revision = '0a10e4e1ea0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects_users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('projects_users', sa.Column('creator', sa.Boolean(), nullable=True))

    # Update existing rows so that everyone is an admin
    op.execute("UPDATE projects_users SET admin = true")
    op.execute("UPDATE projects_users SET creator = true")

    op.alter_column('projects_users', 'admin', nullable=False)
    op.alter_column('projects_users', 'creator', nullable=False)

# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects_users', 'creator')
    op.drop_column('projects_users', 'admin')
    # ### end Alembic commands ###
