"""empty message

Revision ID: efde4e0dd485
Revises: 77346f8d9025
Create Date: 2022-02-07 17:28:22.767875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efde4e0dd485'
down_revision = '77346f8d9025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_notifications_username'), 'progress_notifications', ['username'], unique=False)
    op.create_table('streetview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('service_user', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service')
    )
    op.create_index(op.f('ix_streetview_user_id'), 'streetview', ['user_id'], unique=False)
    op.create_table('streetview_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streetview_id', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['streetview_id'], ['streetview.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streetview_instance_path'), 'streetview_instance', ['path'], unique=False)
    op.create_index(op.f('ix_streetview_instance_streetview_id'), 'streetview_instance', ['streetview_id'], unique=False)
    op.create_index(op.f('ix_streetview_instance_system_id'), 'streetview_instance', ['system_id'], unique=False)
    op.create_table('streetview_organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streetview_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['streetview_id'], ['streetview.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streetview_organization_streetview_id'), 'streetview_organization', ['streetview_id'], unique=False)
    op.create_table('streetview_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('streetview_instance_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bbox', sa.String(), nullable=True),
    sa.Column('sequence_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['streetview_instance_id'], ['streetview_instance.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streetview_sequence_bbox'), 'streetview_sequence', ['bbox'], unique=False)
    op.create_index(op.f('ix_streetview_sequence_sequence_id'), 'streetview_sequence', ['sequence_id'], unique=False)
    op.create_index(op.f('ix_streetview_sequence_streetview_instance_id'), 'streetview_sequence', ['streetview_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streetview_sequence_streetview_instance_id'), table_name='streetview_sequence')
    op.drop_index(op.f('ix_streetview_sequence_sequence_id'), table_name='streetview_sequence')
    op.drop_index(op.f('ix_streetview_sequence_bbox'), table_name='streetview_sequence')
    op.drop_table('streetview_sequence')
    op.drop_index(op.f('ix_streetview_organization_streetview_id'), table_name='streetview_organization')
    op.drop_table('streetview_organization')
    op.drop_index(op.f('ix_streetview_instance_system_id'), table_name='streetview_instance')
    op.drop_index(op.f('ix_streetview_instance_streetview_id'), table_name='streetview_instance')
    op.drop_index(op.f('ix_streetview_instance_path'), table_name='streetview_instance')
    op.drop_table('streetview_instance')
    op.drop_index(op.f('ix_streetview_user_id'), table_name='streetview')
    op.drop_table('streetview')
    op.drop_index(op.f('ix_progress_notifications_username'), table_name='progress_notifications')
    op.drop_table('progress_notifications')
    # ### end Alembic commands ###
