---
version: "3"
services:
  workers:
    image: taccaci/geoapi-workers:${GEOAPI_TAG}
    restart: always
    volumes:
      - /assets:/assets
    env_file: /opt/portal/conf/secrets.env
    environment:
      - FLASK_APP=/app/geoapi/app.py
      - ASSETS_BASE_DIR=/assets
      - GEOAPI_TAG=ENV_GEOAPI_TAG
      - DESIGNSAFE_URL=${DESIGNSAFE_URL}
    stdin_open: true
    tty: true
    container_name: geoapiworkers
    hostname: geoapiworkers
    logging:
      driver: syslog
      options:
        tag: geoapi_workers
    command: "celery -A geoapi.celery_app worker -l info"

  watchtower:
    image: containrrr/watchtower:1.7.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 geoapiworkers
    # Watchtower configuration for development environment. This service monitors
    # and updates the specified containers every 5 min (300s). Staging/Production
    # use specific commit hash tags, so updates are controlled and do not affect
    # those environments. In Development, 'latest' tags are used, enabling
    # Watchtower to automatically update these containers.
    restart: always