---
version: "3"
services:
  workers:
    image: taccaci/geoapi-workers:${GEOAPI_TAG}
    restart: always
    volumes:
      - /assets:/assets
    env_file: /opt/portal/conf/secrets.env
    environment:
      - FLASK_APP=/app/geoapi/app.py
      - ASSETS_BASE_DIR=/assets
      - GEOAPI_TAG=ENV_GEOAPI_TAG
    stdin_open: true
    tty: true
    container_name: geoapiworkers
    hostname: geoapiworkers
    logging:
      driver: syslog
      options:
        tag: geoapi_workers
    command: "celery -A geoapi.celery_app worker -l info"