name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
jobs:
  Geoapi_Unit_Tests:
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: mdillon/postgis:11-alpine
        env:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: dev
        ports:
          -  5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependecies
      run: | 
        python -m pip install --upgrade pip
        pip install -q -r requirements.txt
    - name: Run server-side unit tests
      run: |
        APP_ENV=testing pytest
